### ISSUE TITLE
CLI fails on Python 3.7 and dominoes 6.0.0 with "AttributeError: module 'collections' has no attribute 'abc'"

### ISSUE THREAD

**Issue by abw333** [abw333/dominoes#128]
```
~ ∴ python --version    
Python 3.7.0
~ ∴ pip list            
Package    Version
---------- -------
dominoes   6.0.0  
pip        18.1   
setuptools 40.4.3 
wheel      0.32.2 
~ ∴ dominoes
Traceback (most recent call last):
  File "/Users/abw333/.virtualenvwrapper/dominoes37/bin/dominoes", line 3, in <module>
    import dominoes
  File "/Users/abw333/.virtualenvwrapper/dominoes37/lib/python3.7/site-packages/dominoes/__init__.py", line 13, in <module>
    from dominoes.hand import Hand
  File "/Users/abw333/.virtualenvwrapper/dominoes37/lib/python3.7/site-packages/dominoes/hand.py", line 18, in <module>
    class Hand(collections.abc.Sequence):
  File "/Users/abw333/.virtualenvwrapper/dominoes37/lib/python3.7/collections/__init__.py", line 55, in __getattr__
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
AttributeError: module 'collections' has no attribute 'abc'
```

**Comment by abw333** [comment]
Fixed by https://github.com/abw333/dominoes/pull/129. The snippet below shows that the CLI fails on `dominoes 6.0.0`, but succeeds on `dominoes 6.1.0`.

```
(python37) dominoes (master) ∴ python --version      
Python 3.7.0
(python37) dominoes (master) ∴ pip list              
Package    Version
---------- -------
pip        18.1   
setuptools 40.5.0 
wheel      0.32.2 
(python37) dominoes (master) ∴ pip install dominoes==6.0.0
Collecting dominoes==6.0.0
  Using cached https://files.pythonhosted.org/packages/a7/7a/a97c9acbd5296fca177f8df7c593ec2ce6d9160cb92607cbedd0718653dd/dominoes-6.0.0-py3-none-any.whl
Installing collected packages: dominoes
Successfully installed dominoes-6.0.0
(python37) dominoes (master) ∴ ./bin/dominoes
Traceback (most recent call last):
  File "./bin/dominoes", line 3, in <module>
    import dominoes
  File "/Users/abw333/.virtualenvwrapper/python37/lib/python3.7/site-packages/dominoes/__init__.py", line 13, in <module>
    from dominoes.hand import Hand
  File "/Users/abw333/.virtualenvwrapper/python37/lib/python3.7/site-packages/dominoes/hand.py", line 18, in <module>
    class Hand(collections.abc.Sequence):
  File "/Users/abw333/.virtualenvwrapper/python37/lib/python3.7/collections/__init__.py", line 55, in __getattr__
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
AttributeError: module 'collections' has no attribute 'abc'
(python37) dominoes (master) ∴ pip install dominoes==6.1.0
Collecting dominoes==6.1.0
  Using cached https://files.pythonhosted.org/packages/ea/74/16ce47bf2363cd380a1573352681a0de7c2c9c1b5ccea349c3039272f7e2/dominoes-6.1.0-py3-none-any.whl
Installing collected packages: dominoes
  Found existing installation: dominoes 6.0.0
    Uninstalling dominoes-6.0.0:
      Successfully uninstalled dominoes-6.0.0
Successfully installed dominoes-6.1.0
(python37) dominoes (master) ∴ ./bin/dominoes             
Welcome! Proceeding will clear all text from this terminal session. If you are OK with this, press enter to continue.
```
